### ISSUE TITLE
Missing ability to refresh Json Web Token (JWT)

### ISSUE THREAD

**Issue by mihirpaldhikar** [Bytexl-Teched/Behance-clone-1#1]
## What's the issue?

According to the code written in the [auth.js](https://github.com/Bytexl-Teched/Behance-clone-1/blob/main/bytexl-behance-clone-fullstack-MERN-MongoDB/bytexl-main/Backend/routes/auth.js), the generated and signed JWT is expired after `1hr`. After which the logged in user will not be able to perform the operations. There should be a dedicated route to refresh token automatically either after the token is expired or going to be expired.

## Solution:

There are two types of token:
1. Authorization Token
2. Refresh Token

The expiry of the `authorization token` should be anywhere between `15mins to 1hr`. But the expiry of `refresh token` should be atleast `5 days`. This refresh token will be used to generate new `authorization token` along with that a new `refresh token` should also be generated.

**Comment by Vs-bxl** [comment]
This app is intended to simplify the understanding of building a basic full stack app for students who have never built a full stack web app before. To that end, several choices have been made to avoid topics that are considered 'advanced'. 

Refreshing of tokens have been deliberately not put in place for the sake of pedagogy. It is envisioned that students who are on a more advanced path, can take this basic structure and add refresh token functionality.
