### ISSUE TITLE
JWT is stored insecurly

### ISSUE THREAD

**Issue by mihirpaldhikar** [Bytexl-Teched/Behance-clone-1#2]
## What's the issue?

According to the login written in the [`AuthContext.jsx`](https://github.com/Bytexl-Teched/Behance-clone-1/blob/main/bytexl-behance-clone-fullstack-MERN-MongoDB/bytexl-main/frontend/src/contexts/AuthContext.jsx), the JWT is read from a local storage which is very bad. This is well-known problem with the code.

## The Solution:
The JWT should not be stored in local storage. Instead, it should be securely stored in a HTTP only cookie. Which prevents reading and manipulating the token from the client. Furthermore, the authentication checks should be done on the server side instead of client side. The code written in the `AuthContext` is completely insecure as it enables to bypass the auth checks just by changing the JS loaded on the client.

**Comment by Vs-bxl** [comment]
This app is intended to simplify the understanding of building a basic full stack app for students who have never built a full stack web app before. To that end, several choices have been made to avoid topics that are considered 'advanced'. 

Cookies have been deliberately not put in place for the sake of pedagogy. It is envisioned that students who are on a more advanced path, can take this basic structure and add cookie based authentication as needed.
