### ISSUE TITLE
No Authorization Checks on the Server.

### ISSUE THREAD

**Issue by mihirpaldhikar** [Bytexl-Teched/Behance-clone-1#3]
## What's the issue?

According to the [`auth.js`](https://github.com/Bytexl-Teched/Behance-clone-1/blob/main/bytexl-behance-clone-fullstack-MERN-MongoDB/bytexl-main/Backend/middleware/auth.js) middleware, the only thing that the middleware is doing is to check if JWT token is present in the header and decode it and stores the result in the `req.user` object. Not a single line code written in the [`book.js`](https://github.com/Bytexl-Teched/Behance-clone-1/blob/main/bytexl-behance-clone-fullstack-MERN-MongoDB/bytexl-main/Backend/routes/books.js) is doing the authorization checks for the operations such as updating or deleting  the code. Anyone with the signed JWT can update or delete the books created by the other user for example [here](https://github.com/Bytexl-Teched/Behance-clone-1/blob/d432eedb20d6dc619b91be3f38d32ee147166cfb/bytexl-behance-clone-fullstack-MERN-MongoDB/bytexl-main/Backend/routes/books.js#L100) and [here](https://github.com/Bytexl-Teched/Behance-clone-1/blob/d432eedb20d6dc619b91be3f38d32ee147166cfb/bytexl-behance-clone-fullstack-MERN-MongoDB/bytexl-main/Backend/routes/books.js#L122)

## Solution:

Please add appropriate authorization checks to ensure only the user who has created the entry is able to update or delete the data.

**Comment by Vs-bxl** [comment]
This app is intended to simplify the understanding of building a basic full stack app for students who have never built a full stack web app before. To that end, several choices have been made to avoid topics that are considered 'advanced'. 

Authorization checks have been deliberately not put in place for the sake of pedagogy. It is envisioned that students who are on a more advanced path, can take this basic structure and add authorization code as needed.
